FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY . .
COPY .env .
RUN go mod download
RUN go build -o pvz-service ./cmd

FROM golang:1.24-alpine AS tests

WORKDIR /app
COPY --from=builder /app .
COPY --from=builder /app/migrations ./migrations

COPY .env .

RUN go mod download

CMD ["go", "test", "-v", "-cover", "./..."]
