name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Download dependencies
        run: go mod download

      - name: Generate DTOs / code
        run: make generate-dto

      - name: Run tests
        run: go test -v -race -cover ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Download dependencies
        run: go mod download

      - name: Generate DTOs / code
        run: make generate-dto

      - name: Run linter
        run: golangci-lint run -v ./...